import { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    storeName: 'Shree Nidhi Store',
    villageLedger: 'Village Ledger Passbook',
    digitalKhata: 'Village Ledger Passbook • Digital Khata',
    customerLedger: 'Customer Ledger • Shop Admin',
    villageKhata: 'Village Khata Passbook • Customer',
    english: 'English',
    hindi: 'Hindi',
    kannada: 'Kannada',
    language: 'Language',
    logout: 'Logout',
    passbook: 'Passbook',
    shopAdmin: 'Shop Admin',
    newBill: 'New Bill',
    welcome: 'Welcome to Shree Nidhi Store',
    welcomeSub: 'Digital ledger and khata account',
    verifiedLedger: 'Verified Ledger Account',
    shopOpen: 'Shop Open Now',
    customer: 'Customer',
    accountLogin: 'Account Login',
    shopOwner: 'Shop Owner',
    adminPortal: 'Admin Portal',
    emailAddress: 'Email Address',
    required: 'Required',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    enterPassword: 'Enter your account password to sign in',
    signIn: 'Sign In →',
    signingIn: 'Signing in...',
    needHelp: 'Need Help? Call shop owner',
    call: 'Call',
    totalOutstanding: 'Total Outstanding Due',
    customers: 'Customers',
    todaysReceived: "Today's Received",
    collectedToday: 'Collected today',
    todaysCredit: "Today's Credit",
    givenToday: 'Given today',
    searchCustomer: 'Search customer name or phone...',
    allCustomers: 'All Customers',
    pending: 'Pending',
    completed: 'Completed',
    dueBalance: '↓ Due Balance',
    allClear: '✓ All Clear',
    sendReminder: 'Send Reminder',
    giveCredit: '+ Give Credit',
    takePayment: '− Take Payment',
    advancePay: '+ Advance Pay',
    addNewCustomer: '+ Add New Customer',
    addCustomer: 'Add New Customer',
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    cancel: 'Cancel',
    saveCustomer: 'Save Customer',
    noCustomers: 'No customers found',
    callShopkeeper: 'Call Shopkeeper',
    totalBalanceToPay: 'TOTAL BALANCE TO PAY',
    remainingDue: 'Remaining amount due at shop',
    totalPaidTillNow: 'Total Paid Till Now',
    totalPaymentsMade: 'Total payments made to shopkeeper',
    passbookEntries: 'Passbook Entries',
    statement: 'Statement',
    paid: 'Paid',
    creditPurchase: 'Credit Purchase',
    payment: 'Payment',
    addedToKhata: 'Added to Khata',
    balanceAfter: 'Balance after this entry:',
    due: 'Due',
    accountsVerified: 'Accounts are 100% verified & secure',
    verifiedPassbook:
      'Verified village store digital passbook • Contact shopkeeper directly for any queries',
    currentDue: 'CURRENT DUE',
    verifiedCustomer: 'Verified Customer',
    acceptPayment: '✓ Accept Payment',
    balanceReduction: 'BALANCE REDUCTION',
    balanceIncrease: 'BALANCE INCREASE',
    remainingDuePaid: 'Remaining Due · Paid',
    newDueCredit: 'New Due · Credit',
    paymentAmount: 'Payment Amount',
    creditAmount: 'Credit Amount',
    zeroLedgerFee: 'Zero Ledger Fee',
    paymentMode: 'Payment Mode',
    cash: 'Cash',
    upi: 'UPI / QR Code',
    bankTransfer: 'Bank Transfer',
    notePlaceholder: 'Note / Bill Reference',
    groceryItems: 'Grocery items',
    selectGrocery: 'Select Grocery Items',
    optional: '(Optional)',
    showQuickItems: 'Show Quick Items',
    sendReceipt: 'Send Instant Free WhatsApp & SMS Receipt',
    receiptHint:
      'Customer will receive an instant digital receipt with updated account balance.',
    saveDeduct: 'Save Entry & Deduct',
    saveAdd: 'Save Entry & Add',
    saving: 'Saving...',
    encrypted: '100% Encrypted & Cloud Backed Up Digital Ledger',
    loadingCustomer: 'Loading customer...',
    loadingPassbook: 'Loading passbook...',
    customerRole: 'Customer • Verified Khata',
  },
  hi: {
    storeName: 'श्री निधि स्टोर',
    villageLedger: 'गाँव खाता पासबुक',
    digitalKhata: 'गाँव लेजर पासबुक • डिजिटल खाता',
    customerLedger: 'ग्राहक लेजर • दुकान एडमिन',
    villageKhata: 'गाँव खाता पासबुक • ग्राहक',
    english: 'English',
    hindi: 'हिंदी',
    kannada: 'ಕನ್ನಡ',
    language: 'भाषा',
    logout: 'लॉग आउट',
    passbook: 'पासबुक',
    shopAdmin: 'दुकान एडमिन',
    newBill: 'नया बिल',
    welcome: 'श्री निधि स्टोर में आपका स्वागत है',
    welcomeSub: 'डिजिटल लेजर और खाता',
    verifiedLedger: 'सत्यापित लेजर खाता',
    shopOpen: 'दुकान अभी खुली है',
    customer: 'ग्राहक',
    accountLogin: 'खाता लॉगिन',
    shopOwner: 'दुकान मालिक',
    adminPortal: 'एडमिन पोर्टल',
    emailAddress: 'ईमेल पता',
    required: 'आवश्यक',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूल गए?',
    enterPassword: 'साइन इन करने के लिए पासवर्ड दर्ज करें',
    signIn: 'साइन इन →',
    signingIn: 'साइन इन हो रहा है...',
    needHelp: 'मदद चाहिए? दुकान मालिक को कॉल करें',
    call: 'कॉल',
    totalOutstanding: 'कुल बकाया राशि',
    customers: 'ग्राहक',
    todaysReceived: 'आज की वसूली',
    collectedToday: 'आज एकत्रित',
    todaysCredit: 'आज का उधार',
    givenToday: 'आज दिया गया',
    searchCustomer: 'ग्राहक नाम या फोन खोजें...',
    allCustomers: 'सभी ग्राहक',
    pending: 'बकाया',
    completed: 'पूर्ण',
    dueBalance: '↓ बकाया शेष',
    allClear: '✓ सब साफ',
    sendReminder: 'रिमाइंडर भेजें',
    giveCredit: '+ उधार दें',
    takePayment: '− भुगतान लें',
    advancePay: '+ एडवांस पे',
    addNewCustomer: '+ नया ग्राहक जोड़ें',
    addCustomer: 'नया ग्राहक जोड़ें',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    phone: 'फोन',
    cancel: 'रद्द करें',
    saveCustomer: 'ग्राहक सेव करें',
    noCustomers: 'कोई ग्राहक नहीं मिला',
    callShopkeeper: 'दुकानदार को कॉल करें',
    totalBalanceToPay: 'कुल भुगतान योग्य राशि',
    remainingDue: 'दुकान पर शेष बकाया',
    totalPaidTillNow: 'अब तक कुल भुगतान',
    totalPaymentsMade: 'दुकानदार को कुल भुगतान',
    passbookEntries: 'पासबुक प्रविष्टियाँ',
    statement: 'स्टेटमेंट',
    paid: 'भुगतान',
    creditPurchase: 'उधार खरीदारी',
    payment: 'भुगतान',
    addedToKhata: 'खाते में जोड़ा',
    balanceAfter: 'इस प्रविष्टि के बाद शेष:',
    due: 'बकाया',
    accountsVerified: 'खाते 100% सत्यापित और सुरक्षित हैं',
    verifiedPassbook:
      'सत्यापित गाँव स्टोर डिजिटल पासबुक • किसी भी प्रश्न के लिए दुकानदार से संपर्क करें',
    currentDue: 'वर्तमान बकाया',
    verifiedCustomer: 'सत्यापित ग्राहक',
    acceptPayment: '✓ भुगतान स्वीकार करें',
    balanceReduction: 'शेष घट रहा है',
    balanceIncrease: 'शेष बढ़ रहा है',
    remainingDuePaid: 'शेष बकाया · भुगतान',
    newDueCredit: 'नया बकाया · उधार',
    paymentAmount: 'भुगतान राशि',
    creditAmount: 'उधार राशि',
    zeroLedgerFee: 'शून्य लेजर शुल्क',
    paymentMode: 'भुगतान तरीका',
    cash: 'नकद',
    upi: 'UPI / QR कोड',
    bankTransfer: 'बैंक ट्रांसफर',
    notePlaceholder: 'नोट / बिल संदर्भ',
    groceryItems: 'किराना सामान',
    selectGrocery: 'किराना सामान चुनें',
    optional: '(वैकल्पिक)',
    showQuickItems: 'त्वरित आइटम दिखाएँ',
    sendReceipt: 'मुफ्त WhatsApp और SMS रसीद भेजें',
    receiptHint: 'ग्राहक को अपडेटेड बैलेंस के साथ तुरंत डिजिटल रसीद मिलेगी।',
    saveDeduct: 'सेव करें और काटें',
    saveAdd: 'सेव करें और जोड़ें',
    saving: 'सेव हो रहा है...',
    encrypted: '100% एन्क्रिप्टेड और क्लाउड बैकअप डिजिटल लेजर',
    loadingCustomer: 'ग्राहक लोड हो रहा है...',
    loadingPassbook: 'पासबुक लोड हो रही है...',
    customerRole: 'ग्राहक • सत्यापित खाता',
  },
  kn: {
    storeName: 'ಶ್ರೀ ನಿಧಿ ಸ್ಟೋರ್',
    villageLedger: 'ಗ್ರಾಮ ಖಾತೆ ಪಾಸ್‌ಬುಕ್',
    digitalKhata: 'ಗ್ರಾಮ ಲೆಡ್ಜರ್ ಪಾಸ್‌ಬುಕ್ • ಡಿಜಿಟಲ್ ಖಾತೆ',
    customerLedger: 'ಗ್ರಾಹಕ ಲೆಡ್ಜರ್ • ಅಂಗಡಿ ಅಡ್ಮಿನ್',
    villageKhata: 'ಗ್ರಾಮ ಖಾತೆ ಪಾಸ್‌ಬುಕ್ • ಗ್ರಾಹಕ',
    english: 'English',
    hindi: 'हिंदी',
    kannada: 'ಕನ್ನಡ',
    language: 'ಭಾಷೆ',
    logout: 'ಲಾಗ್ ಔಟ್',
    passbook: 'ಪಾಸ್‌ಬುಕ್',
    shopAdmin: 'ಅಂಗಡಿ ಅಡ್ಮಿನ್',
    newBill: 'ಹೊಸ ಬಿಲ್',
    welcome: 'ಶ್ರೀ ನಿಧಿ ಸ್ಟೋರ್‌ಗೆ ಸ್ವಾಗತ',
    welcomeSub: 'ಡಿಜಿಟಲ್ ಲೆಡ್ಜರ್ ಮತ್ತು ಖಾತೆ',
    verifiedLedger: 'ಪರಿಶೀಲಿತ ಲೆಡ್ಜರ್ ಖಾತೆ',
    shopOpen: 'ಅಂಗಡಿ ಈಗ ತೆರೆದಿದೆ',
    customer: 'ಗ್ರಾಹಕ',
    accountLogin: 'ಖಾತೆ ಲಾಗಿನ್',
    shopOwner: 'ಅಂಗಡಿ ಮಾಲೀಕ',
    adminPortal: 'ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    required: 'ಅಗತ್ಯ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    enterPassword: 'ಸೈನ್ ಇನ್ ಮಾಡಲು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    signIn: 'ಸೈನ್ ಇನ್ →',
    signingIn: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    needHelp: 'ಸಹಾಯ ಬೇಕೇ? ಅಂಗಡಿ ಮಾಲೀಕರಿಗೆ ಕರೆ ಮಾಡಿ',
    call: 'ಕರೆ',
    totalOutstanding: 'ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ',
    customers: 'ಗ್ರಾಹಕರು',
    todaysReceived: 'ಇಂದಿನ ವಸೂಲಿ',
    collectedToday: 'ಇಂದು ಸಂಗ್ರಹಿಸಲಾಗಿದೆ',
    todaysCredit: 'ಇಂದಿನ ಸಾಲ',
    givenToday: 'ಇಂದು ನೀಡಲಾಗಿದೆ',
    searchCustomer: 'ಗ್ರಾಹಕರ ಹೆಸರು ಅಥವಾ ಫೋನ್ ಹುಡುಕಿ...',
    allCustomers: 'ಎಲ್ಲಾ ಗ್ರಾಹಕರು',
    pending: 'ಬಾಕಿ',
    completed: 'ಪೂರ್ಣ',
    dueBalance: '↓ ಬಾಕಿ ಶೇಷ',
    allClear: '✓ ಎಲ್ಲಾ ಸರಿ',
    sendReminder: 'ಜ್ಞಾಪನೆ ಕಳುಹಿಸಿ',
    giveCredit: '+ ಸಾಲ ನೀಡಿ',
    takePayment: '− ಪಾವತಿ ತೆಗೆದುಕೊಳ್ಳಿ',
    advancePay: '+ ಮುಂಗಡ ಪಾವತಿ',
    addNewCustomer: '+ ಹೊಸ ಗ್ರಾಹಕ ಸೇರಿಸಿ',
    addCustomer: 'ಹೊಸ ಗ್ರಾಹಕ ಸೇರಿಸಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    email: 'ಇಮೇಲ್',
    phone: 'ಫೋನ್',
    cancel: 'ರದ್ದುಮಾಡಿ',
    saveCustomer: 'ಗ್ರಾಹಕ ಉಳಿಸಿ',
    noCustomers: 'ಯಾವುದೇ ಗ್ರಾಹಕರು ಕಂಡುಬಂದಿಲ್ಲ',
    callShopkeeper: 'ಅಂಗಡಿಯವರಿಗೆ ಕರೆ ಮಾಡಿ',
    totalBalanceToPay: 'ಪಾವತಿಸಬೇಕಾದ ಒಟ್ಟು ಮೊತ್ತ',
    remainingDue: 'ಅಂಗಡಿಯಲ್ಲಿ ಉಳಿದ ಬಾಕಿ',
    totalPaidTillNow: 'ಇಲ್ಲಿಯವರೆಗೆ ಒಟ್ಟು ಪಾವತಿ',
    totalPaymentsMade: 'ಅಂಗಡಿಯವರಿಗೆ ಒಟ್ಟು ಪಾವತಿಗಳು',
    passbookEntries: 'ಪಾಸ್‌ಬುಕ್ ನಮೂದುಗಳು',
    statement: 'ಸ್ಟೇಟ್‌ಮೆಂಟ್',
    paid: 'ಪಾವತಿ',
    creditPurchase: 'ಸಾಲ ಖರೀದಿ',
    payment: 'ಪಾವತಿ',
    addedToKhata: 'ಖಾತೆಗೆ ಸೇರಿಸಲಾಗಿದೆ',
    balanceAfter: 'ಈ ನಮೂದಿನ ನಂತರ ಶೇಷ:',
    due: 'ಬಾಕಿ',
    accountsVerified: 'ಖಾತೆಗಳು 100% ಪರಿಶೀಲಿತ ಮತ್ತು ಸುರಕ್ಷಿತ',
    verifiedPassbook:
      'ಪರಿಶೀಲಿತ ಗ್ರಾಮ ಅಂಗಡಿ ಡಿಜಿಟಲ್ ಪಾಸ್‌ಬುಕ್ • ಯಾವುದೇ ಪ್ರಶ್ನೆಗೆ ಅಂಗಡಿಯವರನ್ನು ಸಂಪರ್ಕಿಸಿ',
    currentDue: 'ಪ್ರಸ್ತುತ ಬಾಕಿ',
    verifiedCustomer: 'ಪರಿಶೀಲಿತ ಗ್ರಾಹಕ',
    acceptPayment: '✓ ಪಾವತಿ ಸ್ವೀಕರಿಸಿ',
    balanceReduction: 'ಶೇಷ ಕಡಿಮೆಯಾಗುತ್ತಿದೆ',
    balanceIncrease: 'ಶೇಷ ಹೆಚ್ಚಾಗುತ್ತಿದೆ',
    remainingDuePaid: 'ಉಳಿದ ಬಾಕಿ · ಪಾವತಿ',
    newDueCredit: 'ಹೊಸ ಬಾಕಿ · ಸಾಲ',
    paymentAmount: 'ಪಾವತಿ ಮೊತ್ತ',
    creditAmount: 'ಸಾಲ ಮೊತ್ತ',
    zeroLedgerFee: 'ಶೂನ್ಯ ಲೆಡ್ಜರ್ ಶುಲ್ಕ',
    paymentMode: 'ಪಾವತಿ ವಿಧಾನ',
    cash: 'ನಗದು',
    upi: 'UPI / QR ಕೋಡ್',
    bankTransfer: 'ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ',
    notePlaceholder: 'ನೋಟ್ / ಬಿಲ್ ಉಲ್ಲೇಖ',
    groceryItems: 'ದಿನಸಿ ವಸ್ತುಗಳು',
    selectGrocery: 'ದಿನಸಿ ವಸ್ತುಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    optional: '(ಐಚ್ಛಿಕ)',
    showQuickItems: 'ತ್ವರಿತ ವಸ್ತುಗಳನ್ನು ತೋರಿಸಿ',
    sendReceipt: 'ಉಚಿತ WhatsApp ಮತ್ತು SMS ರಸೀದಿ ಕಳುಹಿಸಿ',
    receiptHint: 'ಗ್ರಾಹಕರಿಗೆ ನವೀಕರಿಸಿದ ಬ್ಯಾಲೆನ್ಸ್‌ನೊಂದಿಗೆ ತಕ್ಷಣ ಡಿಜಿಟಲ್ ರಸೀದಿ ಸಿಗುತ್ತದೆ.',
    saveDeduct: 'ಉಳಿಸಿ ಮತ್ತು ಕಡಿತಗೊಳಿಸಿ',
    saveAdd: 'ಉಳಿಸಿ ಮತ್ತು ಸೇರಿಸಿ',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    encrypted: '100% ಎನ್‌ಕ್ರಿಪ್ಟೆಡ್ ಮತ್ತು ಕ್ಲೌಡ್ ಬ್ಯಾಕಪ್ ಡಿಜಿಟಲ್ ಲೆಡ್ಜರ್',
    loadingCustomer: 'ಗ್ರಾಹಕ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    loadingPassbook: 'ಪಾಸ್‌ಬುಕ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    customerRole: 'ಗ್ರಾಹಕ • ಪರಿಶೀಲಿತ ಖಾತೆ',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('sns_lang') || 'en');

  const value = useMemo(
    () => ({
      lang,
      setLang: (next) => {
        localStorage.setItem('sns_lang', next);
        setLang(next);
      },
      t: (key) => translations[lang]?.[key] || translations.en[key] || key,
      label: lang === 'hi' ? 'हिंदी' : lang === 'kn' ? 'ಕನ್ನಡ' : 'English',
    }),
    [lang]
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
